name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go  mod download

    - name: Build
      run: go build -v .

    - name: Test
      # run: echo go test -v .
      run: ./action_experiments

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: action_experiments
        path: action_experiments
