name: Vars

on:
  workflow_dispatch:
    inputs:
defaults:
  run:
    shell: /bin/bash
env:
  foo: value1

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      bar: value2 
      # Looking up `${{ env. }}` from a `env:` section is not allowed.
      # We can use the add-env-vars-action instead:
      # baz: ${{ env.foo }}/baz 
    steps:
      - name: Setup env
        uses: jwulf/add-env-vars-action@master
        with:
          map: '{"baz": "${{ env.foo }}/baz"}'  
      - name: print
        run: |
          echo foo: ${{ env.foo }}
          echo bar: ${{ env.bar }}
          echo baz: ${{ env.baz }}
