name: Vars

on:
  workflow_dispatch:
    inputs:
env:
  foo: value1
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      bar: value2 
    steps:
      - name: print
        run: |
          echo foo: ${{ env.foo }}
          echo bar: ${{ env.bar }}
