name: Vars

on:
  workflow_dispatch:
    inputs:
defaults:
  run:
    shell: bash
env:
  foo: value1

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      bar: value2 
      # Looking up `${{ env. }}` from a `env:` section is not allowed.
      # We can use the $GITHUB_ENV special file instead to simulate this:
      # baz: ${{ env.foo }}/baz 
    steps:
      - name: Setup env
        run: |
          echo "baz=${{ env.foo }}/baz" >> $GITHUB_ENV
      - name: print
        run: |
          echo foo: ${{ env.foo }}
          echo bar: ${{ env.bar }}
          echo baz: ${{ env.baz }}
